### ISSUE TITLE
Error while reading CCPN peaklist

### ISSUE THREAD

**Issue by miguelarbesu** [Farseer-NMR/FarSeer-NMR#258]
Dear Joao and Simon,
I have found what I believe is a parsing error while loading CCPN peaklists. 
FarSeer will throw the "misleading character" error when it finds an asterisk in the "Assign F1" columns. This is typically not a problem unless you have assigned the amide proton of the first residue in the chain, which for some reason is marked with an asterisk.
Since this is the standard behaviour of CCPN when exporting peaklists I would say it's FarSeer's task to read it. 
Best regards.

**Comment by joaomcteixeira** [comment]
yes indeed,
in the near future farseer will parse out misleading characters. For now it
warns the user and points to the file and line where the misleading
character is.

still, this dicision is not trivial because parsing characters silently may
cause trouble. Anyway, manually or guided, the user should decide.

To be implemented.
thanks!
