### ISSUE TITLE
Move Values for fitting to dedicated dialog

### ISSUE THREAD

**Issue by skinnersp** [Farseer-NMR/FarSeer-NMR#268]
Settings for fitting parameter evolution currently live in the General Residue Evolution popup, thus locating them is non-obvious. 
We should create a new popup specifically for fitting residue evolution and put all settings, e.g. starting values, equation selection, x values in there. 
This will make it easier for users to find the fitting functions and use them.
We should also put an option in to use the x values from the parameter tree as fitting values and do the some manipulation of the input using basic heuristics to determine what they are fitting, e.g. split on digit and if uM is part of it, we know it's a concentration in uM.

**Comment by joaomcteixeira** [comment]
Indeed.
I've already partially addresses this in the PR #260 . If you see there there is a `"fitting_settings"` dictionary in the default_config.json file already. We can use it as template to draw this in the GUI. These changes are in the experimental branch https://github.com/joaomcteixeira/FarSeer-NMR/tree/FSv2

In the current GUI the fitting parameters are split in different menus and there is no drop-down option to select the fitting equation and it assumes the Hill by default. So a popup menu to configure this all together as you mentioned is necessary.

However, we have to consider some things:

- performing important changes in the config file will break previous configs from the users. This may not be very problematic though because the user community is still little and we can announce it in the social media.
- changes in the GUI that require changes in the default_config have to be done in combination with changes in the Core.

**Comment by joaomcteixeira** [comment]
Again, just to clear things. The new default_config.json file I refer to is on a experimental branch FSv2 with no connection to the master and is just a proposal to be considered in all the changes you are proposing. Maybe we can already have that as a template.

best

**Comment by joaomcteixeira** [comment]
Tasks registered and catalogued in project, to be addressed as soon as possible.
Reopen if necessary further discussion or and when task becomes under development
Closing for now because it won't be addressed urgently.
