### ISSUE TITLE
gui looks compressed

### ISSUE THREAD

**Issue by eisoab** [Farseer-NMR/FarSeer-NMR#291]
Hi Joao, 

I tried a fresh install on a Centos-7 system incl miniconda  and the whole gui looks compressed with lines half visible etc (not just the 2 upper input fields like we saw last 
thursday. 

Here's a screenshot:
![farseer-linux-open](https://user-images.githubusercontent.com/26520910/46600948-4e977f00-cadb-11e8-8bee-aeced6c28648.png)

-Eiso

**Comment by joaomcteixeira** [comment]
Hello,
Unfortunately the current GUI experiences unexpected outputs on low resolution screens. I am not sure about the resolution of your screen but considering how items are displayed it should be low, or at least no high res. The current GUI was developed to be optimized for high resolution screens. We are looking forward to develop a browser based interface that along with other improvements would solve those issues. Please stay tuning during the next months.

Meanwhile, if you really need to run Farseer-NMR on that screen I can describe you how to use the command line version which is actually very easy it just requires you to copy the data manually instead. Briefly it would be:

1. configure a `spectra` folder where ever you want in your computer with subfolders as you would configure the experimental tree. For example:
```
spectra/
    - 298K
        - mut1
            - 1.csv
            - 2.csv
```
etc..

2. Copy the default_config.json file that you find in the core folder to the folder where you want to perform the calculation. Edit it accordingly, we can discuss privately how to edit the file properly.

3. ./exec_farseer_commandline.sh <path to config file> <path to the folder where spectra folder is>
for example if you have spectra in folder calc1 just type
```
cd calc1 (just navigate to that folder)
/path/to/farseernmr/folder/exec_farseer_commandline.sh MYCONFIG.json .
```
the `.` is important because it tells that the `spectra` folder is `here`.

to run the command line version your input peaklists should be of the ccpnmrv2 format with ALL the columns exported. Name your files in such way that the alphabetical order describes the order of the experiments.

we discuss further on the mailing list.
Thanks for your comment,
Joao
