### ISSUE TITLE
Errors analysing methyl groups of methionines (parsing and chemichal shift values)

### ISSUE THREAD

**Issue by hector-fs** [Farseer-NMR/FarSeer-NMR#306]
Analysing CSP of methyl groups of methionines I found several complications. As all are related with the same peaklists, I'll mention them in the same issue instead of creating several ones:

a)  The standard peaklist for CCPNMR v2 when analysing methyl groups of methionines includes an asterisk in the "Assign F1" column (as an example, it looks like 1MetHe*), generating an issue similar to the mentioned in the issue #258. A manual editing may solve the issue, and as the number of methionines is not that high it should be a nuisance.

b) Once deleting the asterisk, a new error arises, with the following console output:

>    Peaklist [00_Protein][00_298K][00_Sample] "Position F1" values do 
                  not correspond to proton chemical shift values.              
                             + Refer to WET 25 +                         
                                 please visit                              
          github.com/joaomcteixeira/FarSeer-NMR/wiki/WET-List#wet25  
  
I found this to be caused because the "He" proton is, according to FarSeer, not meant to have a chemical shift value around 1.5 and 2.0, which is my case, therefore the error arises. Nevertheless, I found a workaround in order to avoid to modify the position of the peaks: a manual edit of the "Assign F1" column in order to remove the "e" (again, as an example, right now it looks like 1MetH), solves the error.

c) Finally, after the mentioned peaklist modifications, I ran again Farseer, to find a third issue. In this case, the console output is the following:

>    Peaklist [00_Protein][00_298K][00_Sample] "Position F2" values dot   
                  not correspond to nitrogen chemical shift values.            
                          + Refer to WET 25 +                         
                              please visit                              
     github.com/joaomcteixeira/FarSeer-NMR/wiki/WET-List#wet25  

Despite being similar to the second issue, here is no trick to avoid a manual edit of the peaklist. The only way to work with it is to add 100 to each position (as an example modify the position F2 from 15.127 to 115.127), and to modify the "Assign F2" column, as a second error arises:

>  Peaklist [00_Protein][00_298K][00_Sample] "Assign F2" values do not  
                  correspond to nitrogen assignment labels.               
                             + Refer to WET 25 +                
                                 please visit                             
          github.com/joaomcteixeira/FarSeer-NMR/wiki/WET-List#wet25

This is caused because of the value in "Assign F2" is, as an example, 1MetCe instead of 1MetN. I suppose this is because FarSeer is not (yet) able to distinguish between N and C, as most of the development in FarSeer was done with 1H-15N spectra.

**Comment by joaomcteixeira** [comment]
Hello @hector-fs 
Thanks for reporting.

Actually this is not yet an "issue". You are reporting on a feature that has not yet been implemented.
Currently, Farseer-NMR is designed to work only with 1H-15N peaklists, other nomenclatures other than `H` and `N` are not allowed (yet) for backbone atoms.

If you wish to continue with your strategy of _hacking_ Farseer-NMR to allow using `C` atoms, what you need to do next (on top of everything you have already done) is to comment the lines of code that call the checking routines, that is, in the `FarseerCube.py` file comment line 842 `#self._checks_posf1_posf2_nuclei(self.allpeaklists)`.

You can additionally relabel the carbon atoms to `N` in the `Assign F2` column of your peaklists.

**ATTENTION:** this is clearly an _hack_ of the Farseer-NMR functionalities, by doing this you are disabling features that check for input coherency. I advise you to COPY Farseer-NMR installation to another folder and use these _hacks_ only in the project that you are mentioning, so you don't run into unexpected errors on another projects.

Improving Farseer-NMR so that additional nuclei are read is already part of the projects developing route. Nonetheless, we are adding your contributions to the Projects section and we will address it ASAP.

Thanks very much for you feedback!
